[package]
name = "mctool"
version = "0.1.0"
edition = "2024"

[dependencies]
mc-launchermeta = "0.1.1"
reqwest = { version = "0.12.22", features = ["json"] }
serde_json = "1.0.140"
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
