name: Build and Release

on:
  push:
    branches:
      - '**'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
          target: x86_64-unknown-linux-gnu

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Create release archive
        run: |
          mkdir -p dist
          cp target/x86_64-unknown-linux-gnu/release/* dist/ || true
          cd dist
          tar czf release.tar.gz *

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-release-${{ github.sha }}
          name: Auto Release
          files: dist/release.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}