name: Build

permissions: {}

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup update
    - run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config
    - run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        path: target/release/mctool